### ISSUE TITLE
Current NixOS build is broken (both nix build and nixified stack)

### ISSUE THREAD

**Issue by alter2000** [JackMiranda/herms#100]
Running NixOS 19.09 everything up to date since I started typing this, and the nix method outputs:

```
δ nix build -f .
builder for '/nix/store/2f0yxxnlhmp8psq2vgg09y8fx0rh4nkx-herms-1.9.0.4.drv' failed with exit code 1; last 10 log lines:
  version (src/Lang/Strings.hs:140)
  versionShort (src/Lang/Strings.hs:141)
  versionDesc (src/Lang/Strings.hs:142)
  progDesc (src/Lang/Strings.hs:148)
  unsupportedFormat (src/Lang/Strings.hs:149)
  supportedFormats (src/Lang/Strings.hs:150)
 0% (  0 /  2) in 'Lang.Spanish'
Missing documentation for:
  Module header
  spanish (src/Lang/Spanish.hs:5)
[0 built (1 failed), 0.0 MiB DL]  error: build of '/nix/store/2f0yxxnlhmp8psq2vgg09y8fx0rh4nkx-herms-1.9.0.4.drv' failed
```

While stack cannot find `ghc843`.

I don't know if this is beginner friendly (seems like it: bump allowed versions, see if they work, get going), because I'd like to have a go at this, but I'm not sure if it will actually be the best possible outcome.

E: GFM not reddit markdown

**Comment by langston-barrett** [comment]
@alter2000 Good catch! I'd definitely appreciate help on this, and it seems like a reasonably beginner-friendly issue. Feel free to post here if you need any pointers. 

Can you post the full log? (The kind you get from `nix-build` (I'm a little old-fashioned)).

**Comment by alter2000** [comment]
Sure, [here's the log](https://github.com/JackMiranda/herms/files/3774835/nix-build.log.txt). It needs documentation for the `spanish` module (maybe more).
