### ISSUE TITLE
Miscellaneous Tasks

### ISSUE THREAD

**Issue by JackMiranda** [JackMiranda/herms#21]
No issues catch your eye? Check out https://github.com/JackKiefer/herms/blob/master/Contributing.md for other feature ideas

**Comment by hschallh** [comment]
@JackKiefer I'd like to take a crack at nutritional info if that's alright with you.

**Comment by JackKiefer** [comment]
@hschallh Go for it! If you find yourself with any questions, feel free to create a new GitHub Issue about what you're working on. :)

**Comment by hschallh** [comment]
Roger that!

**Comment by renanpvaz** [comment]
Me again, I could translate the texts to portuguese. Should I open an issue for that?

**Comment by siddharthist** [comment]
@renanpvaz No need, feel free just to open a pull request when your work is (partially) ready for review!

**Comment by langston-barrett** [comment]
Let's open more specific issues for any other feature ideas.
