### ISSUE TITLE
Convert oven temperatures in recipe directions between Fahrenheit and Celsius

### ISSUE THREAD

**Issue by JackMiranda** [JackMiranda/herms#39]
This should be an interesting one!
We now have the ability to convert ingredient measurements between imperial and metric. Now, let's take this a step further and add the ability to convert between Fahrenheit and Celsius for oven temperatures inside of recipes' directions! 

This might be a little more involved as it will require parsing through the directions for a phrase like `400°F` or `400 degrees Fahrenheit` and converting it to `204°C` when showing the recipe. Luckily, things like this are pretty straightforward in Haskell, so the hardest part will be familiarizing yourself with the current codebase to get a feel for how to handle things! 

Tips:

- Herm's uses a library called **optparse-applicative for flag handling**
- Check out `src/UnitConversions.hs` to get a feel for how conversions are handled
- `showRecipe` is ultimately the function that gets called to handle these sorts of things

**Comment by CTxD** [comment]
`celsius x = (x - 32) * 1.8`

**Comment by otaviopace** [comment]
Shouldn't this issue be closed since this #92 PR has been merged?

**Comment by langston-barrett** [comment]
Yes, thanks @otaviopace!
